name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js v18
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install dependencies with legacy peer deps
        run: npm install --legacy-peer-deps
      - name: Build Gatsby site
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      