name: Node.js CI
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - name: Install Gatsby
      - run: npm install -g gatsby-cli
      - name: Run build
      - run: npm run build
      - name: Deploy to gh-pages
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}
      